// EstateNova production client
'use strict';

const SUPABASE_URL='https://bttujypzchanhvdmqutv.supabase.co';
const SUPABASE_KEY='sb_publishable_j4O7PGss7-wWXkY5YnwyOw_i3X1p1l0';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const root=document.getElementById('app');
const state={route:'home',id:null,user:null,listings:[],saved:new Set(),convs:[],messages:[],filter:'All',q:'',theme:localStorage.getItem('en_theme')||'light',slide:0,loading:false,channel:null};

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=p=>p?.cover_image_url||p?.image_urls?.[0]||'';
const money=(n,label)=>label||(!n?'Price on request':'₹'+(n>=1e7?(n/1e7).toFixed(2)+' Cr':n>=1e5?(n/1e5).toFixed(2)+' L':Number(n).toLocaleString('en-IN')));
const toast=m=>{const x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2800)};
function parseRoute(){const p=location.pathname.replace(/\/+$/,'')||'/';if(/^\/property\/[^/]+$/.test(p))return ['details',p.split('/')[2]];if(/^\/messages\/[^/]+$/.test(p))return ['chat',p.split('/')[2]];const m={'/':'home','/onboarding':'onboarding','/properties':'properties','/filters':'filters','/saved':'saved','/messages':'messages','/profile':'profile','/profile-edit':'profile-edit','/auth':'auth','/post':'post'};return [m[p]||'home',null]}
[state.route,state.id]=parseRoute();

function path(route,id){return ({home:'/',onboarding:'/onboarding',properties:'/properties',filters:'/filters',saved:'/saved',messages:'/messages',chat:'/messages/'+id,profile:'/profile','profile-edit':'/profile-edit',auth:'/auth',post:'/post',details:'/property/'+id}[route])||'/'}
async function go(route,id){if(state.channel&&route!=='chat'){db.removeChannel(state.channel);state.channel=null}history.pushState({},'',path(route,id));state.route=route;state.id=id||null;await render();if(['home','properties'].includes(route))loadListings()}
window.go=go;
window.addEventListener('popstate',async()=>{[state.route,state.id]=parseRoute();await render()});

function top(){return `<header class="appbar"><button class="brand" onclick="go('home')">Estate<span>Nova</span></button><button class="signin" onclick="${state.user?"go('profile')":"go('auth')"}">${state.user?'Profile':'Sign in'}</button></header>`}
function nav(active){return `<nav class="bottomnav">${[['home','⌂','Home'],['properties','▦','Properties'],['saved','♡','Saved'],['messages','▣','Messages'],['profile','♙','Profile']].map(x=>`<button class="${active===x[0]?'on':''}" onclick="go('${x[0]}')"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</nav>`}
function page(title,back='home'){return `${top()}<div class="pagehead"><button class="back" onclick="go('${back}')">‹</button><h1>${esc(title)}</h1><button class="more" onclick="drawer()">☰</button></div>`}
function empty(title,text,action,label){return `<section class="empty"><div class="emptyicon">⌂</div><h2>${esc(title)}</h2><p>${esc(text)}</p>${action?`<button class="btn primary" onclick="go('${action}')">${esc(label)}</button>`:''}</section>`}

const slides=[
 ['Find The Perfect Property','Explore approved properties that match your needs.','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=88'],
 ['Save What You Love','Keep your favourite properties together in one place.','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=88'],
 ['Talk Directly','Contact listing owners through private conversations.','https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=88']
];
function onboarding(){const s=slides[state.slide];return `<main class="screen onboarding">${top()}<div class="ontext"><small>Find · Buy · Own</small><h1>${s[0]}</h1><p>${s[1]}</p></div><div class="onstage"><div class="ontrack" style="transform:translateX(-${state.slide*100}%)">${slides.map(x=>`<div><img src="${x[2]}" alt=""></div>`).join('')}</div></div><div class="onfoot"><div>${slides.map((_,i)=>`<button class="${i===state.slide?'on':''}" onclick="state.slide=${i};render()"></button>`).join('')}</div><button class="next" onclick="nextSlide()">${state.slide===2?'✓':'→'}</button></div></main>`}
window.nextSlide=async()=>{if(state.slide<2){state.slide++;await render()}else{localStorage.setItem('en_seen','1');go('home')}};

function card(p){return `<article class="property-card" onclick="go('details','${p.id}')"><div class="pc-image">${img(p)?`<img src="${esc(img(p))}" alt="">`:'<div class="noimage">EstateNova</div>'}<button class="heart" onclick="event.stopPropagation();toggleSave('${p.id}')">${state.saved.has(p.id)?'♥':'♡'}</button></div><div class="pc-body"><h3>${esc(p.title)}</h3><strong>${esc(money(p.price,p.price_label))}</strong><p>${esc([p.locality,p.city].filter(Boolean).join(', ')||p.address||'')}</p><div class="stats">${p.area?`<span>${esc(p.area)} ${esc(p.area_unit||'sqft')}</span>`:''}${p.bedrooms?`<span>${esc(p.bedrooms)} Bed</span>`:''}${p.bathrooms?`<span>${esc(p.bathrooms)} Bath</span>`:''}</div></div></article>`}

function home(){const ps=state.listings.slice(0,3);return `<main class="screen">${top()}<section class="homehero"><div class="location">⌖ <span>India</span></div><h1>Find Your<br><em>Dream Home</em></h1><p>Search homes, apartments, land and commercial properties from real EstateNova listings.</p><div class="searchbar"><span>⌕</span><input value="${esc(state.q)}" placeholder="Search properties, locality..." oninput="state.q=this.value" onkeydown="if(event.key==='Enter')searchNow()"><button onclick="go('filters')">☷</button></div><div class="heroactions"><button class="btn primary" onclick="searchNow()">Search properties</button><button class="btn ghost" onclick="go('properties')">Browse all</button></div></section><section class="section"><div class="sectionhead"><h2>Categories</h2><button onclick="go('properties')">See all</button></div><div class="categories">${['Apartment','Villa','House','Land','Office'].map((x,i)=>`<button onclick="state.filter='${x}';go('properties')"><i>${['▥','⌂','⌂','♟','▦'][i]}</i><span>${x}</span></button>`).join('')}</div></section><section class="section"><div class="sectionhead"><h2>Available properties</h2><button onclick="go('properties')">See all</button></div>${ps.length?`<div class="cards">${ps.map(card).join('')}</div>`:empty('No approved properties yet','New listings will appear here after admin approval.')}</section>${nav('home')}</main>`}
window.searchNow=async()=>{state.filter='All';await loadListings();go('properties')};

async function loadListings(){state.loading=true;try{let q=db.from('listings').select('*').eq('approval_status','approved').eq('status','active').order('created_at',{ascending:false});if(state.filter!=='All')q=q.eq('property_type',state.filter);const term=state.q.trim();if(term){const safe=term.replace(/[,()]/g,' ');q=q.or(`title.ilike.%${safe}%,locality.ilike.%${safe}%,city.ilike.%${safe}%,state.ilike.%${safe}%`)}const {data,error}=await q;if(error)throw error;state.listings=data||[]}catch(e){console.error(e);toast('Properties could not be loaded')}finally{state.loading=false;if(['home','properties'].includes(state.route))render()}}
function properties(){return `<main class="screen">${page('Properties')}<div class="content"><div class="searchbar compact"><span>⌕</span><input value="${esc(state.q)}" placeholder="Search properties..." oninput="state.q=this.value" onkeydown="if(event.key==='Enter')loadListings()"><button onclick="go('filters')">☷</button></div><div class="chips">${['All','Apartment','Villa','House','Land','Office'].map(x=>`<button class="${state.filter===x?'on':''}" onclick="state.filter='${x}';loadListings()">${x}</button>`).join('')}</div>${state.loading?'<div class="loading">Loading properties…</div>':state.listings.length?`<div class="list">${state.listings.map(card).join('')}</div>`:empty('No properties found','Try another city, locality or property type.')}</div>${nav('properties')}</main>`}
function filters(){return `<main class="screen">${page('Search & Filters','properties')}<section class="filterbox"><label>Property type</label><div class="chips wrap">${['All','Apartment','Villa','House','Land','Office'].map(x=>`<button class="${state.filter===x?'on':''}" onclick="state.filter='${x}';render()">${x}</button>`).join('')}</div><label>Location / locality</label><input id="filterLocation" class="field" value="${esc(state.q)}" placeholder="e.g. Ranchi, Delhi, Mumbai"><button class="btn primary full" onclick="state.q=document.getElementById('filterLocation').value.trim();go('properties');loadListings()">Show Results</button></section></main>`}

async function details(id){let p=state.listings.find(x=>x.id===id);if(!p){const r=await db.from('listings').select('*').eq('id',id).eq('approval_status','approved').eq('status','active').maybeSingle();p=r.data}if(!p)return `<main class="screen">${page('Property','properties')}${empty('Property unavailable','This listing is no longer publicly available.')}${nav('properties')}</main>`;state.current=p;return `<main class="screen detailpage"><div class="detailimage">${img(p)?`<img src="${esc(img(p))}" alt="${esc(p.title)}">`:'<div class="noimage">EstateNova</div>'}<button class="overlay back" onclick="go('properties')">‹</button><div class="detailtools"><button onclick="toggleSave('${p.id}')">${state.saved.has(p.id)?'♥':'♡'}</button><button onclick="shareProperty()">↗</button></div></div><section class="detailbody"><small>${esc([p.property_type,p.listing_type].filter(Boolean).join(' · '))}</small><h1>${esc(p.title)}</h1><strong class="bigprice">${esc(money(p.price,p.price_label))}</strong><p class="muted">${esc([p.locality,p.city,p.state].filter(Boolean).join(', ')||p.address||'')}</p><div class="facts">${[['area',p.area?p.area+' '+(p.area_unit||'sqft'):'—'],['bedrooms',p.bedrooms??'—'],['bathrooms',p.bathrooms??'—'],['parking',p.parking||'—']].map(x=>`<div><b>${esc(x[1])}</b><small>${x[0]}</small></div>`).join('')}</div><div class="detailsection"><h3>About Property</h3><p>${esc(p.description||'No description provided.')}</p></div><div class="detailsection"><h3>Amenities</h3><p>${esc((p.amenities||[]).join(' · ')||'Not specified')}</p></div><div class="detailactions"><button class="btn ghost" onclick="scheduleVisit('${p.id}')">Schedule Visit</button><button class="btn primary" onclick="startChat('${p.id}')">Contact owner</button></div></section>${nav('properties')}</main>`}
window.shareProperty=async()=>{try{await navigator.share({title:state.current?.title||'EstateNova property',url:location.href})}catch(e){try{await navigator.clipboard.writeText(location.href);toast('Property link copied')}catch(_){}}};

async function toggleSave(id){if(!state.user){toast('Please sign in first');return go('auth')}const has=state.saved.has(id);const r=has?await db.from('favorites').delete().eq('user_id',state.user.id).eq('listing_id',id):await db.from('favorites').insert({user_id:state.user.id,listing_id:id});if(r.error){toast('Could not update saved property');return}has?state.saved.delete(id):state.saved.add(id);render()}
async function loadSaved(){if(!state.user){state.saved=new Set();return}const {data,error}=await db.from('favorites').select('listing_id').eq('user_id',state.user.id);if(!error)state.saved=new Set((data||[]).map(x=>x.listing_id))}
async function saved(){let ids=[...state.saved];let ps=state.listings.filter(p=>ids.includes(p.id));if(ids.length&&ps.length!==ids.length){const r=await db.from('listings').select('*').in('id',ids).eq('approval_status','approved').eq('status','active');ps=r.data||[]}return `<main class="screen">${page('Saved Properties')}${ps.length?`<div class="content"><div class="list">${ps.map(card).join('')}</div></div>`:empty('No saved properties','Tap the heart on a property to save it.','properties','Browse properties')}${nav('saved')}</main>`}

async function loadConversations(){if(!state.user){state.convs=[];return}const r=await db.rpc('get_my_conversations');if(r.error){console.error(r.error);state.convs=[]}else state.convs=r.data||[]}
async function messages(){await loadConversations();return `<main class="screen">${page('Messages')}${state.user?(state.convs.length?`<div class="messages">${state.convs.map(c=>`<button class="conversation" onclick="go('chat','${c.id}')"><img src="${esc(c.other_user_avatar||'')}" alt=""><span><b>${esc(c.other_user_name||'EstateNova member')}</b><small>${esc(c.last_message||c.listing_title||'Conversation')}</small></span><time>${esc((c.last_message_at||'').slice(11,16))}</time></button>`).join('')}</div>`:empty('No conversations yet','Open a property and contact its owner.','properties','Browse properties')):empty('Sign in to view messages','Your conversations are private.','auth','Sign in')}${nav('messages')}</main>`}

async function chat(id){if(!state.user){go('auth');return ''}await loadConversations();const c=state.convs.find(x=>x.id===id);if(!c)return `<main class="screen">${page('Chat','messages')}${empty('Conversation not found','This conversation is not available.')}</main>`;const r=await db.from('messages').select('*').eq('conversation_id',id).order('created_at',{ascending:true});state.messages=r.data||[];if(state.channel)db.removeChannel(state.channel);state.channel=db.channel('estate-chat-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},payload=>{if(!state.messages.some(m=>m.id===payload.new.id)){state.messages.push(payload.new);updateChat()}}).subscribe();await db.rpc('mark_conversation_read',{p_conversation_id:id}).catch(()=>{});return `<main class="screen chatpage"><header class="chathead"><button onclick="go('messages')">‹</button><div><b>${esc(c.other_user_name||'EstateNova member')}</b><small>${esc(c.listing_title||'')}</small></div></header><div class="chatbody" id="chatbody">${state.messages.map(bubble).join('')}</div><form class="composer" onsubmit="sendMessage(event,'${id}')"><input id="messageInput" maxlength="5000" autocomplete="off" placeholder="Write a message…"><button>➤</button></form></main>`}
function bubble(m){return `<div class="bubble ${m.sender_id===state.user.id?'mine':'theirs'}">${esc(m.body)}</div>`}
function updateChat(){const b=document.getElementById('chatbody');if(b){b.innerHTML=state.messages.map(bubble).join('');b.scrollTop=b.scrollHeight}}
window.sendMessage=async(e,id)=>{e.preventDefault();const i=document.getElementById('messageInput'),body=i.value.trim();if(!body||!state.user)return;const r=await db.from('messages').insert({conversation_id:id,sender_id:state.user.id,body});if(r.error)toast('Message could not be sent');else{i.value='';}};

function auth(){return `<main class="screen authpage">${top()}<section class="authbox"><div class="authlogo">Estate<span>Nova</span></div><div class="authswitch"><button class="${state.auth==='login'?'on':''}" onclick="state.auth='login';render()">Sign in</button><button class="${state.auth==='signup'?'on':''}" onclick="state.auth='signup';render()">Create account</button></div><h1>${state.auth==='login'?'Welcome back':'Create your account'}</h1><p>${state.auth==='login'?'Sign in to save, contact and manage your properties.':'Create an EstateNova account to use member features.'}</p>${state.auth==='signup'?'<input id="an" class="field" placeholder="Full name" autocomplete="name">':''}<input id="ae" class="field" type="email" placeholder="Email address" autocomplete="email"><input id="ap" class="field" type="password" placeholder="Password" autocomplete="${state.auth==='login'?'current-password':'new-password'}"><div id="am" class="error"></div><button class="btn primary full" onclick="doAuth()">${state.auth==='login'?'Sign in':'Create account'}</button><button class="btn ghost full" onclick="go('home')">Continue browsing</button></section></main>`}
state.auth='login';
window.doAuth=async()=>{const e=document.getElementById('ae').value.trim(),p=document.getElementById('ap').value,m=document.getElementById('am');if(!e||p.length<6){m.textContent='Enter a valid email and password (6+ characters).';return}const r=state.auth==='login'?await db.auth.signInWithPassword({email:e,password:p}):await db.auth.signUp({email:e,password:p,options:{data:{full_name:document.getElementById('an')?.value.trim()||''}}});if(r.error){m.textContent=r.error.message;return}if(!r.data.session){m.textContent='Account created. Check your email if confirmation is enabled.';return}await syncUser(r.data.user);go('home')};

async function syncUser(user){if(!user){state.user=null;state.saved=new Set();return}let p=(await db.from('profiles').select('*').eq('id',user.id).maybeSingle()).data;if(!p){const full=user.user_metadata?.full_name||'';await db.rpc('ensure_my_profile',{p_full_name:full});p=(await db.from('profiles').select('*').eq('id',user.id).maybeSingle()).data}state.user=p||{id:user.id,email:user.email};await loadSaved()}
async function profile(){return `<main class="screen">${top()}${state.user?`<section class="profilehero"><img src="${esc(state.user.avatar_url||'')}" alt=""><div><h1>${esc(state.user.full_name||'EstateNova member')}</h1><p>${esc(state.user.email||'')}</p><span>${esc(state.user.role||'buyer')}</span></div></section><div class="profilemenu"><button onclick="go('profile-edit')">My Profile <b>›</b></button><button onclick="go('saved')">Saved Properties <b>›</b></button><button onclick="go('post')">Sell / Post Property <b>›</b></button><button onclick="toggleTheme()">Appearance <b>${state.theme==='dark'?'Dark':'Light'}</b></button><button onclick="logout()">Sign out <b>›</b></button></div>`:empty('You are not signed in','Sign in to access your profile.','auth','Sign in')}${nav('profile')}</main>`}
function profileEdit(){if(!state.user)return `<main class="screen">${page('My Profile')}${empty('Sign in required','Please sign in first.','auth','Sign in')}</main>`;return `<main class="screen">${page('My Profile','profile')}<form class="editform" onsubmit="saveProfile(event)"><label>Full name<input id="pn" class="field" value="${esc(state.user.full_name||'')}"></label><label>Phone<input id="pp" class="field" value="${esc(state.user.phone||'')}"></label><label>Company<input id="pc" class="field" value="${esc(state.user.company_name||'')}"></label><label>Bio<textarea id="pb" class="field">${esc(state.user.bio||'')}</textarea></label><label>Profile photo<input id="avatar" class="field" type="file" accept="image/*"></label><div class="readonly"><span>Email</span><b>${esc(state.user.email||'')}</b></div><div class="readonly"><span>Account type</span><b>${esc(state.user.role||'buyer')}</b></div><div class="readonly"><span>Profile ID</span><b>${esc(state.user.id)}</b></div><div id="pm" class="error"></div><button class="btn primary full" type="submit">Save Changes</button></form></main>`}
window.saveProfile=async e=>{e.preventDefault();if(!state.user)return;const m=document.getElementById('pm'),btn=e.submitter;btn.disabled=true;m.textContent='';try{const payload={full_name:document.getElementById('pn').value.trim(),phone:document.getElementById('pp').value.trim(),company_name:document.getElementById('pc').value.trim(),bio:document.getElementById('pb').value.trim(),updated_at:new Date().toISOString()};const f=document.getElementById('avatar').files[0];if(f){if(f.size>5*1024*1024)throw new Error('Profile photo must be 5 MB or smaller.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=state.user.id+'/'+crypto.randomUUID()+'.'+ext;const u=await db.storage.from('avatars').upload(path,f,{upsert:false,contentType:f.type});if(u.error)throw u.error;payload.avatar_url=db.storage.from('avatars').getPublicUrl(path).data.publicUrl}const r=await db.from('profiles').update(payload).eq('id',state.user.id);if(r.error)throw r.error;await syncUser((await db.auth.getUser()).data.user);toast('Profile saved');go('profile')}catch(err){m.textContent=err.message||'Could not save profile'}finally{btn.disabled=false}};
window.logout=async()=>{if(state.channel)db.removeChannel(state.channel);await db.auth.signOut();state.user=null;state.saved=new Set();go('home')};

function post(){if(!state.user)return `<main class="screen">${page('Sell / Post','profile')}${empty('Sign in required','Only signed-in members can publish a property.','auth','Sign in')}</main>`;return `<main class="screen">${page('Sell / Post','profile')}<form class="editform" onsubmit="createListing(event)"><label>Property title<input id="lt" class="field" required></label><label>Property type<select id="ltype" class="field"><option>Apartment</option><option>Villa</option><option>House</option><option>Land</option><option>Office</option></select></label><label>Listing type<select id="lkind" class="field"><option value="sale">Sale</option><option value="rent">Rent</option><option value="lease">Lease</option></select></label><label>Price<input id="lp" class="field" type="number" min="0" required></label><label>Area<input id="la" class="field" type="number" min="0"></label><label>Bedrooms<input id="lb" class="field" type="number" min="0"></label><label>Bathrooms<input id="lba" class="field" type="number" min="0"></label><label>City<input id="lc" class="field" required></label><label>Locality<input id="ll" class="field"></label><label>Address<input id="lad" class="field"></label><label>Description<textarea id="ld" class="field" required></textarea></label><label>Amenities<input id="lam" class="field" placeholder="Parking, Lift, Gym"></label><label>Photos<input id="lf" class="field" type="file" accept="image/*" multiple required></label><div id="lm" class="error"></div><button class="btn primary full" type="submit">Submit for admin approval</button></form></main>`}
window.createListing=async e=>{e.preventDefault();const m=document.getElementById('lm'),btn=e.submitter;btn.disabled=true;m.textContent='';try{const files=[...document.getElementById('lf').files].slice(0,10);if(!files.length)throw new Error('Add at least one property photo.');const row={owner_id:state.user.id,title:document.getElementById('lt').value.trim(),property_type:document.getElementById('ltype').value,listing_type:document.getElementById('lkind').value,price:+document.getElementById('lp').value||0,area:+document.getElementById('la').value||null,bedrooms:+document.getElementById('lb').value||null,bathrooms:+document.getElementById('lba').value||null,city:document.getElementById('lc').value.trim(),locality:document.getElementById('ll').value.trim(),address:document.getElementById('lad').value.trim(),description:document.getElementById('ld').value.trim(),amenities:document.getElementById('lam').value.split(',').map(x=>x.trim()).filter(Boolean),approval_status:'pending',status:'draft'};const ins=await db.from('listings').insert(row).select().single();if(ins.error)throw ins.error;const urls=[];for(let i=0;i<files.length;i++){const f=files[i];if(f.size>10*1024*1024)throw new Error('Each property photo must be 10 MB or smaller.');const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const storagePath=state.user.id+'/'+ins.data.id+'/'+crypto.randomUUID()+'.'+ext;const up=await db.storage.from('property-images').upload(storagePath,f,{upsert:false,contentType:f.type});if(up.error)throw up.error;const url=db.storage.from('property-images').getPublicUrl(storagePath).data.publicUrl;urls.push(url);const li=await db.from('listing_images').insert({listing_id:ins.data.id,storage_path:storagePath,public_url:url,sort_order:i});if(li.error)throw li.error}const upd=await db.from('listings').update({cover_image_url:urls[0]||null,image_urls:urls}).eq('id',ins.data.id);if(upd.error)throw upd.error;m.className='success';m.textContent='Submitted for admin approval.';setTimeout(()=>go('profile'),700)}catch(err){m.textContent=err.message||'Could not create listing'}finally{btn.disabled=false}};

window.scheduleVisit=async id=>{if(!state.user)return go('auth');const message=prompt('Tell the owner when you would like to visit:');if(!message?.trim())return;const p=state.listings.find(x=>x.id===id)||state.current;const seller=p?.owner_id;if(!seller)return toast('Owner information is unavailable');const r=await db.from('inquiries').insert({listing_id:id,buyer_id:state.user.id,seller_id:seller,message:message.trim(),buyer_phone:state.user.phone||null,buyer_email:state.user.email||null});toast(r.error?r.error.message:'Visit request sent')};
window.startChat=async id=>{if(!state.user)return go('auth');const message=prompt('Write your first message:');if(!message?.trim())return;const r=await db.rpc('start_conversation',{p_listing_id:id,p_message:message.trim()});if(r.error){toast(r.error.message);return}const cid=typeof r.data==='string'?r.data:r.data?.id||r.data?.[0]?.id;if(cid)go('chat',cid);else{await loadConversations();const c=state.convs[0];if(c)go('chat',c.id);else toast('Conversation could not be opened')}};

function drawer(){const x=document.createElement('div');x.className='drawerback';x.innerHTML=`<aside class="drawer"><button class="drawerclose" onclick="this.closest('.drawerback').remove()">×</button><div class="drawerbrand">Estate<span>Nova</span></div>${[['home','Home'],['properties','Properties'],['saved','Saved Properties'],['messages','Messages'],['profile','My Profile'],['post','Sell / Post']].map(x=>`<button onclick="this.closest('.drawerback').remove();go('${x[0]}')">${x[1]}<b>›</b></button>`).join('')}<button onclick="this.closest('.drawerback').remove();toggleTheme()">Dark / Light mode <b>◐</b></button></aside>`;x.onclick=e=>{if(e.target===x)x.remove()};document.body.append(x)}
window.drawer=drawer;
window.toggleTheme=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('en_theme',state.theme);applyTheme();render()};
function applyTheme(){document.documentElement.dataset.theme=state.theme}
applyTheme();

async function render(){try{applyTheme();let html='';switch(state.route){case'home':html=home();break;case'onboarding':html=onboarding();break;case'properties':html=properties();break;case'filters':html=filters();break;case'saved':html=await saved();break;case'details':html=await details(state.id);break;case'messages':html=await messages();break;case'chat':html=await chat(state.id);break;case'profile':html=await profile();break;case'profile-edit':html=profileEdit();break;case'auth':html=auth();break;case'post':html=post();break;default:state.route='home';html=home()}root.innerHTML=html;if(state.route==='chat')setTimeout(()=>updateChat(),20)}catch(e){console.error(e);root.innerHTML=empty('Something went wrong','Please refresh and try again.')}}
async function init(){try{const r=await db.auth.getSession();await syncUser(r.data.session?.user||null)}catch(e){console.error('auth init',e)}await render();loadListings()}
db.auth.onAuthStateChange((event,session)=>{queueMicrotask(async()=>{try{await syncUser(session?.user||null);if(['home','properties','saved','messages','profile','profile-edit'].includes(state.route))await render()}catch(e){console.error('auth state',e)}})});
init();
